name: Merge Bot

on:
  pull_request:
    types:
      - labeled

jobs:
  merge:
    runs-on: ubuntu-latest
    name: Merge
    steps:
      - name: Integration check
        uses: squalrus/merge-bot@v0.4.5
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          labels: ready, merge
          blocking_labels: do not merge
          checks_enabled: true
          method: squash
          delete_source_branch: true