pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - base = master
      - check-success=Analyze (javascript)
      - check-success=CodeQL
      - check-success=ESLint
      - check-success=Build
      - check-success=Run linters
      
    actions:
      merge:
        method: rebase
