pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - base = master
      - check-success=Lint on pull request
    actions:
      merge:
        method: rebase
