pull_request_rules:
  - name: Automatic merge on approval
    conditions:
      - "#approved-reviews-by>=1"
      - base = master
      - check-success=Build
      - check-success=Run linters
  - name: comment when a pull request cannot be merged
    conditions:
      - conflict
    actions:
      comment:
        message: @{{author}} Your PR is in conflict and cannot be merged.
      
    actions:
      merge:
        method: rebase
